### ISSUE TITLE
from web3 import Web3, KeepAliveRPCProvider

### ISSUE THREAD

**Issue by Saadinr** [MysticRyuujin/EthHack#2]
hi help pls

Traceback (most recent call last):
  File "EthHack.py", line 7, in <module>
    from web3 import Web3, KeepAliveRPCProvider
ImportError: cannot import name 'KeepAliveRPCProvider'

**Comment by MysticRyuujin** [comment]
Hey,

That provider has been depreciated, you'll now need to use [HTTPProvider](https://web3py.readthedocs.io/en/stable/providers.html#web3.providers.rpc.HTTPProvider)

Also, the Python version is like 60x slower than the .NET version, so I've basically stopped using it.
